name: Shot-PL
version: 1.1.7
main: com.example.ShotPL
api-version: 1.20
authors: [shotxd]
description: A Minecraft plugin for shot-pl
commands:
  verify:
    description: Verify your account with a code
    usage: /verify <code>
    permission: shotpl.verify
permissions:
  shotpl.verify:
    description: Allows players to verify their account
    default: true 